# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    error_controller: App\Controller\ErrorController::show

    session:
        enabled: true
        handler_id: app.session_handler.redis
        cookie_secure: auto
        cookie_samesite: lax
    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
